MCR-2134 update dependencies
MyCoRe-Org/mir pull request #1042
Opened 2024-08-06 10:46 UTC by yagee-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2134).

Requires https://github.com/MyCoRe-Org/mycore/pull/2212

2024-08-06 10:47 UTC, yagee-de commented
Solr 9.6.1 does not work currently @sebhofmann

2024-08-08 10:22 UTC, toKrause approved these changes

2024-08-08 13:37 UTC, sebhofmann requested changes
Should also upgrade the docker solr versions.

2024-08-09 05:35 UTC, yagee-de commented
> Should also upgrade the docker solr versions.

Updated docker-compose.prod.yml to 2023.06.x and Postgres 16
and docker-compose.yml to SOLR 9.6.1 and Postgres 16

2024-08-12 08:42 UTC, sebhofmann approved these changes

2024-08-12 08:47 UTC, merged