Issues/mir 924 abstract improvements
MyCoRe-Org/mir pull request #523
Opened 2020-09-04 09:21 UTC by yagee-de

[Link to jira](https://mycore.atlassian.net/browse/MIR-924).

2020-09-04 12:10 UTC, fluetze approved these changes

2020-09-04 15:29 UTC, kkrebs requested changes
Title will be migrated but shown not any longer in metadata page. There goes something wrong?!

2020-09-07 12:26 UTC, yagee-de commented on mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java
> +        XMLOutputter xout = new XMLOutputter(Format.getPrettyFormat());
Codacy found an issue: [Avoid unused local variables such as 'xout'.](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867)

2020-09-07 12:26 UTC, yagee-de commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867&bid=20036924)

2020-09-07 12:26 UTC, yagee-de commented on mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java
> +import java.io.ByteArrayInputStream;
Codacy found an issue: [Avoid unused imports such as 'java.io.ByteArrayInputStream'](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867)

2020-09-07 12:26 UTC, yagee-de commented on mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java
> +import java.io.ByteArrayInputStream;
Codacy found an issue: [Unused import - java.io.ByteArrayInputStream.](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867)

2020-09-07 12:33 UTC, yagee-de commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867&bid=20036924)

2020-09-07 12:33 UTC, yagee-de commented on mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java
> +import java.io.ByteArrayInputStream;
Codacy found an issue: [Avoid unused imports such as 'java.io.ByteArrayInputStream'](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867)

2020-09-07 12:33 UTC, yagee-de commented on mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java
> +        XMLOutputter xout = new XMLOutputter(Format.getPrettyFormat());
Codacy found an issue: [Avoid unused local variables such as 'xout'.](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867)

2020-09-07 12:33 UTC, yagee-de commented on mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java
> +import java.io.ByteArrayInputStream;
Codacy found an issue: [Unused import - java.io.ByteArrayInputStream.](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867)

2020-09-07 12:36 UTC, yagee-de commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867&bid=20036924)

2020-09-07 13:48 UTC, kkrebs approved these changes

2020-09-07 13:52 UTC, yagee-de commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6124867&bid=20036924)

2020-09-07 13:52 UTC, merged