MIR-939 do not include migration commands by default
MyCoRe-Org/mir pull request #526
Opened 2020-09-10 13:45 UTC by yagee-de

[Link to jira](https://mycore.atlassian.net/browse/MIR-939).

2020-09-14 09:50 UTC, fluetze requested changes
I'd prefer to keep the last migration commands still active.
When they are included by default, I initually see the commands, run them, then disable them locally.
When they are nit included by default, I might not recognize them, must include them, run them, then exclude them again. More work, more space for errors.

2020-09-23 08:51 UTC, yagee-de commented
> I'd prefer to keep the last migration commands still active.
> When they are included by default, I initually see the commands, run them, then disable them locally.
> When they are nit included by default, I might not recognize them, must include them, run them, then exclude them again. More work, more space for errors.

How can you exclude them afterwards without loosing future updates? As you can only append to a property and not remove a part I was for exclude by default.

2020-09-24 14:30 UTC, kkrebs approved these changes

2020-09-25 07:33 UTC, fluetze approved these changes

2020-09-25 07:34 UTC, kkrebs commented
after short discussion we decided, that current migration command should be activated by default.

2020-09-25 07:34 UTC, merged