MIR-959 derivate classification should have higher acl priority
MyCoRe-Org/mir pull request #551
Opened 2020-11-16 17:24 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MIR-959).

2020-11-18 10:19 UTC, yagee-de requested changes

2020-11-18 10:19 UTC, yagee-de commented on mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java
> +        return getAccessCategory(accessMappedCategories,
should be like
```java
return Optional.ofNullable(derivateId)
    .flatMap(id -> getAccessCategory(getAccessMappedCategories(id.getTypeId(), permission, accessClasses), id))
    .or(() -> getAccessCategory(getAccessMappedCategories(objectId.getTypeId(), permission, accessClasses), objectId));

```

2020-11-18 16:39 UTC, kkrebs approved these changes
successfully tested

2020-11-19 16:18 UTC, yagee-de commented on mir-module/src/main/java/org/mycore/mir/authorization/MIRStrategy.java
> +        return getAccessCategory(getAccessMappedCategories(id.getTypeId(), permission, accessClasses), id);
There is no fallback to object?

2021-01-04 12:51 UTC, yagee-de approved these changes

2021-01-04 12:51 UTC, merged