MIR-1101 thumbnail derivate should be preferred in search results
MyCoRe-Org/mir pull request #707
Opened 2022-01-20 09:01 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MIR-1101).

2022-01-20 09:28 UTC, rsteph-de commented
Just for the records: On RosDok (before switching to IIIF-Thumbnail-API) I used an extra solr field "cover_url" and decided which derivate / file to display during indexing. 
It contained the complete URL-Path (without baseURL) to the image - so it was very easy to include into the search result page.

2022-01-26 20:43 UTC, kkrebs commented on mir-module/src/main/resources/xsl/response-mir.xsl
> +                  <!-- if not, then the content type decides a icon -->
please readd missing code line
<div class="hit_icon" style="background-image: url('{$WebApplicationBaseURL}images/icons/icon_common.png');" />

the hit icon overlay is designed only as an overlay to this common icon

2022-01-26 20:44 UTC, kkrebs requested changes
see comment

2022-01-28 16:34 UTC, kkrebs approved these changes

2022-01-28 17:11 UTC, merged