MIR-1151 Rework mods name search
MyCoRe-Org/mir pull request #776
Opened 2022-06-16 14:55 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MIR-1151).

2022-07-19 13:57 UTC, sebhofmann commented on mir-webapp/src/main/vue/name-search/public/index.html
> +    <link rel="stylesheet" href="http://localhost:8291/mir/rsc/sass/mir-layout/scss/flatmir-flatly.min.css">
index.html is only used for testing its not actually used when the component is built.

2022-07-19 13:57 UTC, sebhofmann commented on mir-webapp/src/main/vue/name-search/public/index.html
> +      </script>
index.html is only used for testing its not actually used when the component is built.

2022-07-20 08:47 UTC, golsch requested changes

2022-07-20 08:47 UTC, golsch commented on mir-module/src/main/resources/config/mir/messages_de.properties
> +mir.editor.addIdentifier            = Identifier Hinzuf\u00FCgen
Respect to "mir.editor.person.applyPerson", "ID" instead of "Identifier"?

2022-07-20 08:47 UTC, golsch commented on pom.xml
> +    <node.version>v12.22.12</node.version>
Does not belong directly to it, but this props are redefined in MIR, may we should use definitions of mycore-parent, according to https://github.com/MyCoRe-Org/mycore/pull/1623

2022-07-20 08:47 UTC, golsch commented on mir-webapp/src/main/vue/name-search/src/App.vue
> +          <button :id="`search-${this.nameIndex}`" type="button" class="btn btn-outline-secondary"
Oher templates use "btn-secondary" here

2022-07-20 08:47 UTC, golsch commented on mir-webapp/src/main/vue/name-search/src/App.vue
> +    console.log("Clicked outside!")
I would generally suggest to remove the logs in production.

2022-07-20 08:47 UTC, golsch commented on mir-webapp/src/main/vue/name-search/src/api/ProxiedOrcidProvider.ts
> +        return (<any>window)["webApplicationBaseURL"] + "servlets/MIROrcidServlet"
Type `any` leads to ugly outputs during building. I would suggest to annotate them at least so that they are no longer displayed

2022-07-20 08:47 UTC, golsch commented on mir-webapp/src/main/vue/name-search/src/api/LocalSearchProvider.ts
> +            const count = array[i+1] as number;
unused

2022-07-28 07:15 UTC, golsch approved these changes

2022-09-21 10:15 UTC, kkrebs approved these changes

2022-09-27 07:34 UTC, merged