MIR-1096 Add highly visible edit button for metadata
MyCoRe-Org/mir pull request #780
Opened 2022-06-22 10:01 UTC by toKrause

[Link to jira](https://mycore.atlassian.net/browse/MIR-1096).

2022-06-22 11:41 UTC, toKrause commented
Sorry, I've gotten a bi git-confused and accidentally removed the branch for the original PR for this issue. Had to make a new one.

2023-02-15 13:05 UTC, TiloNN commented
@toKrause 
Can you rebase your branch to 2022.06.2-SNAPSHOT please.

2023-02-15 15:53 UTC, toKrause commented
> @toKrause Can you rebase your branch to 2022.06.2-SNAPSHOT please.

done

2023-04-25 16:16 UTC, kkrebs requested changes
looks good for  me, but info button did not work

2024-08-08 10:16 UTC, closed without merging