MIR-1306 sword dependencies using javax
MyCoRe-Org/mir pull request #996
Opened 2024-04-17 13:59 UTC by eckstueck

[Link to jira](https://mycore.atlassian.net/browse/MIR-1306).

2024-04-17 16:39 UTC, rsteph-de requested changes
see my comment in JIRA ticket

2024-04-18 07:18 UTC, yagee-de approved these changes

2024-04-22 05:51 UTC, yagee-de commented
> > > see my comment in JIRA ticket
> > 
> > 
> > If this PR fixes the problem, it's looking like an easy fix to be applied in other applications as well. You're right, that this is fundamentally a mycore-sword problem that should be fixed there. BUT I would rather see a working workaround merged soon in MIR than to wait for a harder to implement general fix in mycore-sword.
> 
> Why is it harder to fix this in mycore? It think would be almost the same pr, just with changes in mycore-sword, no?

In mycore is no WAR-package just JAR-packages. So either you have to provide a fat-jar or fork 5 dependencies and provide a fix.

2024-05-07 14:12 UTC, rsteph-de approved these changes

2024-05-07 14:12 UTC, merged